### ISSUE TITLE
config-css can't load fontawesome.css

### ISSUE THREAD

**Issue by khenderick** [easy-webpack/config-css#6]
In my `package.json`, `"font-awesome": "^4.6.3"` is a dependency and `"@easy-webpack/config-css": "^2.3.2"` is a devDependency. Both dev and prod have `require('@easy-webpack/config-css')({ filename: 'styles.css', allChunks: true, sourceMap: false })` in the `webpack.config.js`

As my splash screen uses font-awesome, I have to require font-awesome's css file in my html's head.

```
...
<head>
    <title><%= webpackConfig.metadata.title %></title>
    ...
    <link rel="stylesheet" href="<%= require('font-awesome/css/font-awesome.css') %>"/>
   ...
</head>
<body>
   ...
   <i class="fa fa-spinner fa-spin text-center"></i>
...
```

However, this raises following error during `npm start`:

```
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plug  in, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
```

That page refers me to the fact that you should have the right plugins loaded etc, but that's what I expect config-css to do for me. Any thoughts?

**Comment by niieani** [comment]
No need to add any `<link rel>` to your index.html. In Webpack, we use loaders, and `config-css` uses one. All you need to do is `import 'font-awesome/css/font-awesome.css'`  in one of your entry files, such as `main.js`.
